import type { Metadata } from "next";
import { Barlow_Condensed, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/templates";

const barlowNormal = Barlow_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-barlow",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowNormal.variable} ${robotoMono.variable} antialiased bg-base-dark`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
